# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.CharField(default='stuff', max_length=255),
            preserve_default=False,
        ),
    ]
