# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_trip_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateField(),
        ),
    ]
